//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomResourceStateMetrics) DeepCopyInto(out *CustomResourceStateMetrics) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomResourceStateMetrics.
func (in *CustomResourceStateMetrics) DeepCopy() *CustomResourceStateMetrics {
	if in == nil {
		return nil
	}
	out := new(CustomResourceStateMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CustomResourceStateMetrics) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomResourceStateMetricsConfigMap) DeepCopyInto(out *CustomResourceStateMetricsConfigMap) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomResourceStateMetricsConfigMap.
func (in *CustomResourceStateMetricsConfigMap) DeepCopy() *CustomResourceStateMetricsConfigMap {
	if in == nil {
		return nil
	}
	out := new(CustomResourceStateMetricsConfigMap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomResourceStateMetricsList) DeepCopyInto(out *CustomResourceStateMetricsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CustomResourceStateMetrics, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomResourceStateMetricsList.
func (in *CustomResourceStateMetricsList) DeepCopy() *CustomResourceStateMetricsList {
	if in == nil {
		return nil
	}
	out := new(CustomResourceStateMetricsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CustomResourceStateMetricsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomResourceStateMetricsSpec) DeepCopyInto(out *CustomResourceStateMetricsSpec) {
	*out = *in
	out.ConfigMap = in.ConfigMap
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]runtime.RawExtension, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomResourceStateMetricsSpec.
func (in *CustomResourceStateMetricsSpec) DeepCopy() *CustomResourceStateMetricsSpec {
	if in == nil {
		return nil
	}
	out := new(CustomResourceStateMetricsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomResourceStateMetricsStatus) DeepCopyInto(out *CustomResourceStateMetricsStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomResourceStateMetricsStatus.
func (in *CustomResourceStateMetricsStatus) DeepCopy() *CustomResourceStateMetricsStatus {
	if in == nil {
		return nil
	}
	out := new(CustomResourceStateMetricsStatus)
	in.DeepCopyInto(out)
	return out
}
