apiVersion: ksm.jtyr.io/v1
kind: CustomResourceStateMetrics
metadata:
  name: non-map-arrays
spec:
  configMap:
    name: kube-state-metrics-customresourcestate-config
  resources:
    - groupVersionKind:
        group: myteam.io
        kind: Foo
        version: v1
      labelsFromPath:
        name:
          - metadata
          - name
      metrics:
        - name: ref_info
          help: Reference to other Foo
          each:
            type: Info
            info:
              path:
                - spec
                - refs
              labelsFromPath:
                ref: []
